[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
tournament_betting_system = "FL7hr4LCxSTk2p2xwbk2Qy6dnGeBxc6Daz223dzfTncz"
token_faucet = "TokenFaucetProgram1111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/tournament_betting_system.ts'"
